# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['__init__.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('core/locales/*.toml', 'core/locales'),
        ('requirements.txt', '.'),
    ],
    hiddenimports=[
        'tkinter',
        'tkinter.ttk',
        'tkinter.messagebox',
        'tkinter.filedialog',
        'tkinter.scrolledtext',
        'pyftpdlib',
        'pyftpdlib.handlers',
        'pyftpdlib.servers',
        'pyftpdlib.authorizers',
        'tomli',
        'tomli_w',
        'tomllib',
        'core',
        'core.config',
        'core.logger',
        'core.server_manager',
        'core.i18n',
        'core.server',
        'core.user_manager',
        'gui',
        'gui.main',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # 排除不需要的模块以减小文件大小
        'unittest',
        'test',
        'tests',
        'distutils',
        'setuptools',
        'pip',
        'wheel',
        'pkg_resources',
        'pydoc',
        'doctest',
        'sqlite3',
        'xml',
        'xmlrpc',
        'html',
        'http.server',
        'urllib.parse',
        'urllib.request',
        'email',
        'multiprocessing',
        'concurrent.futures',
        'asyncio',
        'curses',
        'readline',
        'rlcompleter',
        'pdb',
        'profile',
        'cProfile',
        'pstats',
        'trace',
        'tracemalloc',
        'turtle',
        # 保留tkinter相关模块以确保GUI正常工作
         # 'tkinter.dnd',
         # 'tkinter.colorchooser', 
         # 'tkinter.commondialog',
         # 'tkinter.simpledialog',
         # 'tkinter.font',
        'idlelib',
        'lib2to3',
    ],
    noarchive=False,
    optimize=2,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='ftp2python-debug',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)